<h1>Signup Form</h1>
<form id="signup-form">
    <div class="form-group row">
        <label for="signup-name">Name</label>
        <input class="form-control" type="text" name="signup-name" placeholder="Enter Name">
    </div>
    <br>
    <div class="form-group row">
        <label for="signup-date">Date</label><br>
        <input class="form-control" type="date" name="signup-date">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
